version: "3.7"
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./src/test/resources:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=olga
      - MYSQL_PASSWORD=warm